src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmintours/', include('myadmin.urls', namespace='myadmin')),
    path('summernote/', include('django_summernote.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('tours.urls', namespace='tours')),
    path('inf/', include('site_info.urls', namespace='site_info')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
from django.urls import path, include
from .views import home_page, single_tour, tours_list

app_name = 'tours'

urlpatterns = [
    path('', home_page, name='home-page'),
    path('tours/<str:tour_slug>', single_tour , name='single_tour'),
    path('all_tours_experiences/', tours_list , name='tours_list'),
]

tours/models.py
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from multiselectfield import MultiSelectField


class Language(models.Model):
    title = models.CharField(max_length=3, unique=True)
    image = models.ImageField(upload_to='languages')

    def __str__(self):
        return self.title


class City(models.Model):
    name        = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    image       = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.name

ALLOWED_ITEMS = (
    ('pets','Pets Allowed'),
    ('tour_guide','Tour Guide'),
    ('accessibiliy','Accessibiliy'),
    ('audio_guide','Audio guide'),
    ('none','None of the records (if you check this one all of choices above will be ignored)'),
)
ALLOWED_AGES = (
    ('seniors','Seniors'),
    ('adults','Adults'),
    ('children','Children'),
    ('enfant','Enfant'),
)
ALLOWED_DAYS = (
    ('0','Sunday'),
    ('1','Monday'),
    ('2','Tuesday'),
    ('3','Wednesday'),
    ('4','Thursday'),
    ('5','Friday'),
    ('6','Saturday'),
    ('7', 'Daily'),
)
TOUR_TAGS = (
    ('none','NONE'),
    ('POPULAR','POPULAR'),
    ('SELLS OUT FAST','SELLS OUT FAST'),
    ('NEW','NEW'),
    ('BEST SELLER','BEST SELLER'),
)
DAYS_IN_ADVANCED = (
    ('0','None'),
)
CATEGORIES = (
    ('tour','Tour'),
    ('experience','Experience'),
)
for i in range (1,31):
    DAYS_IN_ADVANCED+= (("{}".format(i),"{}".format(i)),)
class Tour(models.Model):
    title               = models.CharField(max_length=200, help_text="this title is only to help you know wihch tour is this")
    from_date           = models.DateField(blank=True, null=True)
    to_date             = models.DateField(blank=True, null=True)
    from_time           = models.TimeField(blank=True, null=True)
    to_time             = models.TimeField(blank=True, null=True)
    availability        = MultiSelectField(choices=ALLOWED_DAYS)
    allowed_items       = MultiSelectField(choices=ALLOWED_ITEMS, blank=True, null=True)
    allowed_ages        = MultiSelectField(choices=ALLOWED_AGES)

    age_senior          = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 90+")
    price_senior        = models.IntegerField(blank=True, null=True, default=0)
    age_adult           = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_adult         = models.IntegerField(blank=True, null=True, default=0)
    age_children        = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_children      = models.IntegerField(blank=True, null=True, default=0)
    age_infant          = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_infant        = models.IntegerField(blank=True, null=True, default=0)

    hours               = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")
    minutes             = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")
    days                = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")

    days_in_advance     = models.CharField(max_length=20,choices=DAYS_IN_ADVANCED)
    languages           = models.ManyToManyField(Language, blank=True)
    category            = models.CharField(max_length=20,choices=CATEGORIES)
    tag                 = models.CharField(max_length=200, choices=TOUR_TAGS)
    image               = models.ImageField(upload_to='image/tours')
    image1              = models.ImageField(upload_to='image/tours')
    image2              = models.ImageField(upload_to='image/tours')
    image3              = models.ImageField(upload_to='image/tours')
    wallpaper           = models.ImageField(upload_to='image/tours', blank=True, null=True)
    active              = models.BooleanField(default=True)
    feautured           = models.BooleanField(default=False, help_text="check this one if you want it to be displayed at home page")

    def __str__(self):
        return str(self.title)


class TourGallery(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="img/tours_gallery")

    def __str__(self):
        return "Image for {}".format(self.tour.title)

class TourDetail(models.Model):
    tour        = models.ForeignKey(
                    Tour, on_delete=models.SET_NULL, blank=True, null=True)
    Language    = models.ForeignKey(
                    Language, on_delete=models.SET_NULL, blank=True, null=True)
    title       = models.CharField(max_length=200)
    city        = models.ForeignKey(
                    City, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField()
    summary     = models.TextField()
    included    = models.TextField()
    excluded    = models.TextField()
    slug        = models.SlugField(unique=True, blank=True, null=True, help_text="leave it empty if you don't have a good keyword in your head")

    def __str__(self):
        return self.title



def tourDetail_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(tourDetail_pre_save, sender=TourDetail)

tours/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, HttpResponse
from .utils import change_currency
from .models import Language, Tour, TourDetail, City
from tours.models import TourDetail
from site_info.models import Slider
from django.shortcuts import  get_object_or_404
from reviews.forms import ReviewForm
from reviews.models import Review


# Create your views here.
langs = settings.LANGUAGES

def change_currency_post(request):
    currency = 1
    if request.method == 'POST':
        currency = request.POST.get('currency')
        request.session['currency'] = change_currency(currency)
        if currency == 'USD':
            request.session['currency_short'] = '$'
        elif currency == 'EUR':
            request.session['currency_short'] = '€'
        else:
            request.session['currency_short'] = currency
    else:
        if 'currency' not in request.session:
            request.session['currency'] = '1'
            request.session['currency_short'] = '€'


def home_page(request, *args, **kwargs):
    change_currency_post(request)

    # lang = Language.objects.filter(title=request.LANGUAGE_CODE).first()
    lang = get_object_or_404(Language, title=request.LANGUAGE_CODE)

    feautured_tours = Tour.objects.filter(feautured=True)
    active_tours = feautured_tours.filter(active=True)
    active_exps = feautured_tours.filter(active=True)

    active_tours = active_tours.filter(category='tour')
    active_experiences = active_exps.filter(category='experience')

    tours = TourDetail.objects.filter(Language_id=lang.id).filter(
        tour__in=active_tours).order_by('-id')[:6]
    experiences = TourDetail.objects.filter(Language_id=lang.id).filter(
        tour__in=active_experiences).order_by('-id')[:6]

    context = {
        'tours': tours,
        'experiences': experiences
    }
    return render(request, 'tours/home.html', context)


def single_tour(request,error=None, **kwargs):
    change_currency_post(request)
    error = error
    tour = get_object_or_404(TourDetail, slug=kwargs['tour_slug'])
    av = []
    for item in tuple(tour.tour.availability):
        av.append(item)
    review_form = ReviewForm()
    reviews = Review.objects.filter(tour=tour.tour).order_by('-id')[:6]
    context = {
        'tour': tour,
        'availability': av,
        'review_form' : review_form,
        'reviews': reviews,
        'error': error
    }
    return render(request, 'tours/single_tour.html', context)


def tours_list(request):
    change_currency_post(request)
    tours        = Tour.objects.all()
    lang         = get_object_or_404(Language, title=request.LANGUAGE_CODE)
    tours_detail = TourDetail.objects.filter(Language=lang)

    if 'type' in request.GET:
        tours = tours.filter(category=request.GET['type']) if request.GET['type'] != 'all' else tours
    if 'city' in request.GET:
        city = get_object_or_404(City, name=request.GET['city']) if request.GET['city'] != 'all' else tours_detail
        tours_detail = tours_detail.filter(city=city) if request.GET['city'] != 'all' else tours_detail

    tours_detail = tours_detail.filter(tour__in=tours)

    paginator = Paginator(tours_detail, 15)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    f_tours = paginator.get_page(page)
    
    context = {
        'tours': f_tours
    }
    return render(request, 'tours/tours_list.html', context)

tours/templates/tours/about.html
{% extends "base.html" %}

tours/templates/tours/home.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load my_filters %}

{% block styles %}
<link rel="stylesheet" href="{% static 'site/css/animate.css' %}">
{% endblock styles %}

{% block content %}

<div class="intro ">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h3>{% trans 'Tickets to culture and entertainment from your smartphone. No printing, no waiting.' %}</h3>
            </div>
          </div>
        </div>
      </div>
      
      <div class="container">
      
        <div class="row">
          <div class="col-12 text-center">
            <h4 class="text-uppercase font-weight-bold p-3 text-muted">{% trans 'our top tours' %}</h4>
            <hr>
          </div>
        </div>
      
        <div class="row">
      
          {% for tour in tours %}
          
          <div class="col-md-4 animated tour-box-container">
            <a href="{% url 'tours:single_tour' tour.slug %}" class="tour-box">
              <span class="h6 text-center bg-{{tour.tour.tag}}">{{tour.tour.tag}}</span>
              <div class="card" style="width: 18rem;">
                <img class="card-img-top" height="230" src="{{ tour.tour.image.url }}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{tour.title}}</h5>
                  <p class="card-text text-muted">{{tour.summary|truncatewords:10}}.</p>
                  <div class="row">
                    <div class="rating col text-left">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star-half"></i>
                    </div>
                    <div class="price col text-right">
                      <span>
                        <sup>
                          {% if request.session.currency_short %} {{ request.session.currency_short }} {% else %} $ {% endif %}
                      </sup>
                        {{ tour.tour.price_adult|multiply:request.session.currency }}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>

          {% endfor %}
      
        </div>
      
      
      
        <div class="row">
          <div class="col-12 text-center">
            <h4 class="text-uppercase font-weight-bold p-3 text-muted">{% trans 'our top experiences' %}</h4>
            <hr>
          </div>
        </div>
      
        <div class="row">
      
          {% for tour in experiences %}
          
            <div class="col-md-4 animated tour-box-container">
              <a href="{% url 'tours:single_tour' tour.slug %}" class="tour-box">
                <span class="h6 text-center bg-{{tour.tour.tag}}">{{tour.tour.tag}}</span>
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" height="230" src="{{ tour.tour.image.url }}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{tour.title}}</h5>
                    <p class="card-text text-muted">{{tour.summary|truncatewords:10}}.</p>
                    <div class="row">
                      <div class="rating col text-left">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half"></i>
                      </div>
                      <div class="price col text-right">
                        <sup>
                          {% if request.session.currency_short %} {{ request.session.currency_short }} {% else %} $ {% endif %}
                      </sup>
                        {% if request.session.currency %} {{ tour.tour.price_adult|multiply:request.session.currency }} {% else %} {{ tour.tour.price_adult
                        }} {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </a>
            </div>

          {% endfor %}
      
        </div>
      
        <div class="row">
          <div class="col-12 text-center">
            <div class="form-group">
              <a href="{% url 'tours:tours_list' %}" class="btn btn-lg btn-primary bg-main">Show all <i class="fa fa-plus"></i></a>
            </div>
          </div>
        </div>
      
      </div>
      
      
      <div class="row" id="newsletter">
        <div class="col-12 text-center">
          <div class="newsteler">
            <h3 class="text-center p-3">Newsletter</h3>
            <p class="text-muted">Stay up to date with the latest tours and experiences.</p>
            <form action="#" class="col-md-4  offset-md-4 col-xs-12" @submit.prevent="submitForm" method="POST"> {% csrf_token %}
              <div class="form-group">
                <input type="email" class="form-control" placeholder="Enter your email here." required v-model="email">
              </div>
              <div class="form-group">
                <input type="submit" class="btn btn-lg" value="Subscribe">
              </div>
            </form>
          </div>
        </div>
      </div>
      
      
      <div class="container">
        <h4 class="text-center p-3">A video from travel with friends presenting the beauty of morocco</h4>
        <div class="row p-3">
          <div class="col">
            <iframe width="100%" height="500vh" src="https://www.youtube-nocookie.com/embed/ZE81dWxNnMQ?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          </div>
        </div>
      </div>

{% endblock content %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script src="{% static 'site/js/main.js' %}"></script>
{% endblock scripts %}

tours/templates/tours/tours_list.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load my_filters %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'site/css/all_tours.css' %}">
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row mt-3">
      <div class="card col-12">
        <div class="card-body">
          <h6>Filter by</h6>
          <form class="row" method="get">
            <div class="form-group col-md-3">
              <span>City:</span>
              <select class="form-control" name="city">
                <option value="all">--SELECT A CITY--</option>
                <option value="all">All</option>
                <option value="marrakech">Marrakech</option>
              </select>
            </div>

            <div class="form-group col-md-3">
              <span>Type:</span>
              <select class="form-control" name="type">
                <option value="all">--SELECT A TYPE--</option>
                <option value="all">All</option>
                <option value="tour">Tour</option>
                <option value="experience">Experience</option>
              </select>
            </div>

            <div class="form-group col-md-6">
              <br>
              <button type="submit" type="submit" class="btn btn-block bg-main text-white">Filter</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="row mt-3">
      <div class="card col-12">
        <div class="card-body">
          <div class="col-md-10 offset-md-1 col-xs-12">

            {% for tour in tours %}
            
            <a href="{% url 'tours:single_tour' tour.slug %}" class="tour m-3">
              <div>
                <img height="200px" class="rounded float-left mr-3"
                src="{{ tour.tour.image.url }}" alt="">
                <span class="h6 text-center text-white p-1 bg-{{tour.tour.tag}} tag">{{tour.tour.tag}}</span>
                <h4>{{ tour.title }}</h4>
                <p class="text-muted">{{ tour.summary }}</p>
                <p><b> <i class="fa fa-compass"></i> {{ tour.city }}</b></p>
                <p>
                  <b class="pull-right h4">
                    <sup>
                      {% if request.session.currency_short %} {{ request.session.currency_short }} {% else %} $ {% endif %}
                    </sup>{% if request.session.currency %} {{ tour.tour.price_adult|multiply:request.session.currency }} {% else %} {{ tour.tour.price_adult
                    }} {% endif %}
                  </b>
                </p>
              </div>
            </a>
            <hr >

            {% endfor %}

          
          </div>
        </div>

        <nav aria-label="Page navigation text-center row">
          <ul class="pagination m-3  text-center">
            {% if tours.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ tours.previous_page_number }}">Prev</a>
              </li>
            {% endif %}
            {% for page in tours.paginator.page_range %}
                <li {% if page == tours.number %} class="active page-item" {% endif %}>
                    <a class="page-link" href="?page={{ page }}">{{page}}</a>
                </li>
            {% endfor %}
            {% if tours.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ tours.next_page_number }}">Next</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      <!-- end pagination-->



      </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}

{% endblock scripts %}