myadmin/urls.py
from django.urls import  path
from django.contrib.auth.decorators import login_required
from .views import (home, add_tour,
                    add_detail, tours_list, show_detail_page,
                    update_tour, delete_tour, tour_details, tour_detail_delete,
                    tour_detail_update, check_voucher, all_orders,languages_view,
                    add_language, delete_language)


app_name = 'myadmin'

urlpatterns = [
    path('', login_required(home) , name='myadmin-home'),
    path('add-tour', login_required(add_tour) , name='myadmin-add-tour'),
    path('update-tour/<int:id>', login_required(update_tour) , name='myadmin-update-tour'),
    path('delete-tour/<int:id>', login_required(delete_tour) , name='myadmin-delete-tour'),
    path('add-detail', login_required(add_detail) , name='myadmin-add-detail'),
    path('tours-list', login_required(tours_list) , name='myadmin-tours-list'),
    path('detail-form/<int:tour>', login_required(show_detail_page) , name='myadmin-detail-form'), # made this only to send tour from tours list
    path('tour-details/<int:tour>', login_required(tour_details) , name='myadmin-tour-details'),
    path('tour-details/delete/<int:detail>', login_required(tour_detail_delete) , name='myadmin-detail-delete'),
    path('tour-details/update/<int:detail>', login_required(tour_detail_update) , name='myadmin-detail-update'),
    path('check-voucher', login_required(check_voucher), name='check-voucher'),
    path('all-orders', login_required(all_orders), name='all-orders'),
    path('languages', login_required(languages_view), name='languages'),
    path('languages/add', login_required(add_language), name='add-language'),
    path('languages/update/<int:id>', login_required(add_language), name='update-language'),
    path('languages/delete/<int:id>', login_required(delete_language), name='delete-language'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmintours/', include('myadmin.urls', namespace='myadmin')),
    path('summernote/', include('django_summernote.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('tours.urls', namespace='tours')),
    path('inf/', include('site_info.urls', namespace='site_info')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
from django.urls import path, include
from .views import home_page, single_tour, tours_list

app_name = 'tours'

urlpatterns = [
    path('', home_page, name='home-page'),
    path('tours/<str:tour_slug>', single_tour , name='single_tour'),
    path('all_tours_experiences/', tours_list , name='tours_list'),
]

myadmin/models.py
from django.db import models

# Create your models here.

tours/models.py
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from multiselectfield import MultiSelectField


class Language(models.Model):
    title = models.CharField(max_length=3, unique=True)
    image = models.ImageField(upload_to='languages')

    def __str__(self):
        return self.title


class City(models.Model):
    name        = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    image       = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.name

ALLOWED_ITEMS = (
    ('pets','Pets Allowed'),
    ('tour_guide','Tour Guide'),
    ('accessibiliy','Accessibiliy'),
    ('audio_guide','Audio guide'),
    ('none','None of the records (if you check this one all of choices above will be ignored)'),
)
ALLOWED_AGES = (
    ('seniors','Seniors'),
    ('adults','Adults'),
    ('children','Children'),
    ('enfant','Enfant'),
)
ALLOWED_DAYS = (
    ('0','Sunday'),
    ('1','Monday'),
    ('2','Tuesday'),
    ('3','Wednesday'),
    ('4','Thursday'),
    ('5','Friday'),
    ('6','Saturday'),
    ('7', 'Daily'),
)
TOUR_TAGS = (
    ('none','NONE'),
    ('POPULAR','POPULAR'),
    ('SELLS OUT FAST','SELLS OUT FAST'),
    ('NEW','NEW'),
    ('BEST SELLER','BEST SELLER'),
)
DAYS_IN_ADVANCED = (
    ('0','None'),
)
CATEGORIES = (
    ('tour','Tour'),
    ('experience','Experience'),
)
for i in range (1,31):
    DAYS_IN_ADVANCED+= (("{}".format(i),"{}".format(i)),)
class Tour(models.Model):
    title               = models.CharField(max_length=200, help_text="this title is only to help you know wihch tour is this")
    from_date           = models.DateField(blank=True, null=True)
    to_date             = models.DateField(blank=True, null=True)
    from_time           = models.TimeField(blank=True, null=True)
    to_time             = models.TimeField(blank=True, null=True)
    availability        = MultiSelectField(choices=ALLOWED_DAYS)
    allowed_items       = MultiSelectField(choices=ALLOWED_ITEMS, blank=True, null=True)
    allowed_ages        = MultiSelectField(choices=ALLOWED_AGES)

    age_senior          = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 90+")
    price_senior        = models.IntegerField(blank=True, null=True, default=0)
    age_adult           = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_adult         = models.IntegerField(blank=True, null=True, default=0)
    age_children        = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_children      = models.IntegerField(blank=True, null=True, default=0)
    age_infant          = models.CharField(max_length=100,blank=True, null=True, help_text="Eg: 14-50")
    price_infant        = models.IntegerField(blank=True, null=True, default=0)

    hours               = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")
    minutes             = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")
    days                = models.CharField(max_length=100,blank=True, null=True, help_text="Leave it empty if it is not availble on the tour")

    days_in_advance     = models.CharField(max_length=20,choices=DAYS_IN_ADVANCED)
    languages           = models.ManyToManyField(Language, blank=True)
    category            = models.CharField(max_length=20,choices=CATEGORIES)
    tag                 = models.CharField(max_length=200, choices=TOUR_TAGS)
    image               = models.ImageField(upload_to='image/tours')
    image1              = models.ImageField(upload_to='image/tours')
    image2              = models.ImageField(upload_to='image/tours')
    image3              = models.ImageField(upload_to='image/tours')
    wallpaper           = models.ImageField(upload_to='image/tours', blank=True, null=True)
    active              = models.BooleanField(default=True)
    feautured           = models.BooleanField(default=False, help_text="check this one if you want it to be displayed at home page")

    def __str__(self):
        return str(self.title)


class TourGallery(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="img/tours_gallery")

    def __str__(self):
        return "Image for {}".format(self.tour.title)

class TourDetail(models.Model):
    tour        = models.ForeignKey(
                    Tour, on_delete=models.SET_NULL, blank=True, null=True)
    Language    = models.ForeignKey(
                    Language, on_delete=models.SET_NULL, blank=True, null=True)
    title       = models.CharField(max_length=200)
    city        = models.ForeignKey(
                    City, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField()
    summary     = models.TextField()
    included    = models.TextField()
    excluded    = models.TextField()
    slug        = models.SlugField(unique=True, blank=True, null=True, help_text="leave it empty if you don't have a good keyword in your head")

    def __str__(self):
        return self.title



def tourDetail_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(tourDetail_pre_save, sender=TourDetail)

myadmin/views.py
from django.shortcuts import render, redirect
from checkout.models import Billing
import datetime
from django.db.models import Sum
from .forms import TourForm, DetailsForm, CheckVoucherForm, LanguageForm
from tours.models import Tour, TourDetail, Language
from checkout.models import Billing
from checkout.models import Voucher
from django.shortcuts import  get_object_or_404
import datetime


def home(request):
    orders = Billing.objects.order_by('-id')[:30]
    orders_today = Billing.objects.filter(date_order=datetime.datetime.now().date())
    today_income = orders_today.aggregate(Sum('amount'))
    total_orders = Billing.objects.all()
    total_income = total_orders.aggregate(Sum('amount'))
    context = {
        'orders': orders,
        'orders_today': orders_today,
        'today_income': today_income,
        'total_orders': total_orders,
        'total_income': total_income
    }
    return render(request, 'myadmin/home.html', context)


def add_tour(request, *args, **kwargs):
    form = TourForm()
    if request.method == 'POST':
        form = TourForm(request.POST, request.FILES)
        if form.is_valid():
            tour = form.save()
            if request.POST['action'] == 'next':
                tour = get_object_or_404(Tour, id=tour.id)
                form_detail = DetailsForm()
                return render(request, 'myadmin/tours/adddetails.html', {'tour': tour, 'form': form_detail})
            else:
                tours = Tour.objects.order_by('-id')
                return render(request, 'myadmin/tours/all-tours.html', {'added': True, "tours": tours})
    context = {
        'form': form
    }
    return render(request, 'myadmin/tours/add.html', context)


def update_tour(request, id):
    tour = get_object_or_404(Tour, id=id)
    if request.method == 'POST':
        form = TourForm(request.POST or None, request.FILES, instance=tour)
    else:
        form = TourForm(request.POST or None, instance=tour)
    if form.is_valid():
        form.save()
    return render(request, 'myadmin/tours/add.html', {"form": form, "update": True, "tour": tour})


def delete_tour(request, id):
    if request.method == 'POST':
        tour = get_object_or_404(Tour, id=id)
        tour.delete()
        tours = Tour.objects.order_by('-id')
        return render(request, 'myadmin/tours/all-tours.html', {'deleted': True, "tours": tours})
    return render(request, 'myadmin/tours/delete_tour.html')


def show_detail_page(request, tour):
    tour = get_object_or_404(Tour, id=tour)
    form_detail = DetailsForm()
    return render(request, 'myadmin/tours/adddetails.html', {'tour': tour, 'form': form_detail})


def add_detail(request):
    if request.method == 'POST':
        form = DetailsForm(request.POST)
        tour = get_object_or_404(Tour, id=request.POST['tour'])
        if form.is_valid():
            detail = form.save()
            detail.tour = tour
            detail.save()
            form = DetailsForm()
            return render(request, 'myadmin/tours/adddetails.html', {'form': form, 'success': True})
    else:
        return redirect("myadmin:myadmin-home")


def tours_list(request):
    tours = Tour.objects.order_by('-id')
    return render(request, 'myadmin/tours/all-tours.html', {'tours': tours})


def tour_details(request, tour):
    tour = Tour.objects.get(id=tour)
    details = TourDetail.objects.filter(tour=tour)
    context = {
        'tour' : tour,
        'details': details
    }
    return render(request, 'myadmin/details/tour-details.html', context)


def tour_detail_delete(request, detail):
    if request.method == 'POST':
        tour_detail = get_object_or_404(TourDetail, id=detail)
        tour_detail.delete()
        tours = Tour.objects.order_by('-id')
        return render(request, 'myadmin/tours/all-tours.html', {'deleted': True, "tours": tours})
    return render(request, 'myadmin/tours/delete_tour.html')


def tour_detail_update(request, detail):
    updated = "0"
    detail = get_object_or_404(TourDetail, id=detail)
    form = DetailsForm(request.POST or None, instance=detail)
    if form.is_valid():
        form.save()
        updated = "1"
    return render(request, 'myadmin/tours/adddetails.html', {"form": form, "updated": updated, "detail": detail})


def check_voucher(request):
    form = CheckVoucherForm()
    if request.method == 'POST':
        form = CheckVoucherForm(request.POST)
        if form.is_valid():
            no = request.POST['voucher_no']
            exists = '-'
            voucher = None
            try:
                voucher = Voucher.objects.get(No=no)
                exists = True
            except Voucher.DoesNotExist:
                exists = False

            context = {
                'form': form,
                'exists': exists,
                'voucher': voucher
            }

            return render(request, 'myadmin/voucher/check_voucher.html', context)

    return render(request, 'myadmin/voucher/check_voucher.html', {'form': form})


def all_orders(request):
    orders = Billing.objects.order_by('-id')
    context = {
        'orders':orders
    }
    return render(request, 'myadmin/orders/all_orders.html', context)


def languages_view(request):
    languages = Language.objects.all()
    context = {
        'languages': languages
    }
    return render(request, 'myadmin/language/home.html', context)

def add_language(request, *args, **kwargs):
    form = LanguageForm()
    if 'id' in kwargs:
        language = get_object_or_404(Language, id=kwargs['id'])
        form = LanguageForm(request.POST or None, instance=language)
        if request.method == 'POST':
            form = LanguageForm(request.POST, request.FILES, instance=language)
            if form.is_valid():
                form.save()
                return render(request, 'myadmin/language/home.html', {'languages': Language.objects.all()})
    if request.method == 'POST':
        form = LanguageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/myadmintours/languages')
    context = {
        'form': form
    }
    return render(request, 'myadmin/language/add.html', context)

def delete_language(request, id):
    language = get_object_or_404(Language, id=id)
    language.delete()
    return redirect('/myadmintours/languages')

myadmin/templates/myadmin/tours/add.html
{% extends "myadmin/base.html" %}

{% block content %}
<style media="screen">
ul {
  list-style: none
}
</style>

<div class="row" id="app">
    <div class="col-md-6 offset-md-3">
        <div class="card m-b-30">
            <div class="card-body">
              {% if form.errors %}
                <div class="alert alert-danger">
                  {{form.errors}}
                </div>
              {% endif %}
                <form method="post" {% if update %} action="{% url 'myadmin:myadmin-update-tour' tour.id %}" {% endif %} enctype="multipart/form-data" >{% csrf_token %}
                  <div class="form-group">
                    title
                    {{form.title}}
                  </div>
                  <!-- <div class="form-group row">
                    <div class="col">
                      From date
                      {{form.from_date}}
                    </div>
                    <div class="col">
                      to date
                      {{form.to_date}}
                    </div>
                  </div> -->
                  <div class="form-group row">
                    <div class="col">
                      From time
                      {{form.from_time}}
                    </div>
                    <div class="col">
                      to time
                      {{form.to_time}}
                    </div>
                  </div>
                  <hr>
                  <div class="form-group row">
                    <div class="col">
                      availability <hr>
                      {{form.availability}}
                    </div>
                    <div class="col">
                      allowed ages <hr>
                      {{form.allowed_ages}}
                    </div>
                  </div>
                  <h5>Prices</h5>
                  <hr>
                  <div class="form-group row">
                    <div class="col">
                      Age senior
                      {{form.age_senior}}
                    </div>
                    <div class="col">
                      Price senior
                      {{form.price_senior}}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col">
                      Age adult
                      {{form.age_adult}}
                    </div>
                    <div class="col">
                      Price adult
                      {{form.price_adult}}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col">
                      Age children
                      {{form.age_children}}
                    </div>
                    <div class="col">
                      Price children
                      {{form.price_children}}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col">
                      Age infant
                      {{form.age_infant}}
                    </div>
                    <div class="col">
                      Price infant
                      {{form.price_infant}}
                    </div>
                  </div>
                  <hr>
                  <div class="form-group row">
                    <div class="col">
                      Hours
                      {{form.hours}}
                    </div>
                    <div class="col">
                      minutes
                      {{form.minutes}}
                    </div>
                    <div class="col">
                      days
                      {{form.days}}
                    </div>
                    <div class="col">
                      days in advance
                      {{form.days_in_advance}}
                    </div>
                  </div>
                  <div class="form-group">
                    Languages
                    {{form.languages}}
                  </div>
                  <hr>
                  <div class="form-group row">
                    <div class="col">
                      Category
                      {{form.category}}
                    </div>
                    <div class="col">
                      Tag
                      {{form.tag}}
                    </div>
                  </div>
                  <hr>
                  <h4>Images</h4>
                  <div class="form-group row">
                    <div class="col">
                      Main Image
                      {{form.image}}
                    </div>
                    <div class="col">
                      Image 1
                      {{form.image1}}
                    </div>
                    <div class="col">
                      Image 2
                      {{form.image2}}
                    </div>
                    <div class="col">
                      Image 3
                      {{form.image3}}
                    </div>
                    <div class="col">
                      wallpaper
                      {{form.wallpaper}}
                    </div>
                  </div>
                  <hr>
                  <div class="form-group">
                    <div class="col">
                      Active?
                      {{form.active}}
                    </div>
                    <div class="col">
                      feautured?
                      {{form.feautured}}
                    </div>
                  </div>
                    {% if update %}
                      <button class="btn btn-info" name="action" value="next">Update</button>
                    {% else %}
                      <button class="btn btn-success" name="action" value="save">Save and exit</button>
                      <button class="btn btn-info" name="action" value="next">Next - Add details</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

{% block script %}
<script>
    $(document).ready(function(){
      $('#id_languages').addClass('form-control')
      $('#id_category').addClass('form-control')
      $('#id_tag').addClass('form-control')
      $('#id_image').addClass('form-control')
      $('#id_image1').addClass('form-control')
      $('#id_image2').addClass('form-control')
      $('#id_image3').addClass('form-control')
      $('#id_wallpaper').addClass('form-control')

      $('#id_availability_7').click(function(){
        $('#id_availability input:checkbox').not(this).prop('checked', this.checked);
      });
    })

</script>
{% endblock script %}
{% endblock content%}

myadmin/templates/myadmin/tours/adddetails.html
{% extends "myadmin/base.html" %}

{% block content %}
{% if success %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success!</strong> Detail added succefuly.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
{% if updated  == "1" %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success!</strong> Detail updated succefuly.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="row" id="app">
  <div class="col-md-6 offset-md-3" >
      <div class="card m-b-30">
        <div class="card-body">
          {% if form.errors %}
            <div class="alert alert-danger">
              {{form.errors}}
            </div>
          {% endif %}
          <h3>Details for: {{tour}}</h3>
            <form method="post" {% if updated %}action="{% url 'myadmin:myadmin-detail-update' detail.id %}" {% else %}action="{% url 'myadmin:myadmin-add-detail' %}"{% endif %} >{% csrf_token %}
              <input type="hidden" name="tour" value="{{tour.id}}">
              <div class="form-group">
                Language
                {{form.Language}}
              </div>
              <div class="form-group">
                Title
                {{form.title}}
              </div>
              <div class="form-group">
                  City
                  {{form.city}}
              </div>
              <div class="form-group">
                description
                {{form.description}}
              </div>
              <div class="form-group">
                summary
                {{form.summary}}
              </div>
              <div class="form-group">
                included
                {{form.included}}
              </div>
              <div class="form-group">
                excluded
                {{form.excluded}}
              </div>
              <div class="form-group">
                {% if updated %}
                  <button type="submit" class="btn btn-success btn-block">Update</button>
                {% else %}
                  <button type="submit" class="btn btn-success btn-block">Save</button>
                {% endif %}
              </div>
            </form>
      </div>
    </div>
  </div>
</div>
{% block script %}
  <script>
    $(document).ready(function(){
        $('#id_Language').addClass("form-control")
        $('#id_title').addClass("form-control")
        $('#id_city').addClass("form-control")
    })
  </script>
{% endblock %}
{% endblock %}

myadmin/templates/myadmin/tours/all-tours.html
{% extends "myadmin/base.html" %}

{% block content %}
{% if deleted %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Success!</strong> Object deleted successfully.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
{% if added %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success!</strong> Tour Added successfully.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="row" id="app">
  <div class="col-md-6 offset-md-3">
    <div class="card m-b-30">
      <div class="card-body">
        <table class="table">
          <thead>
            <th>Image</th>
            <th>Title</th>
            <th>Type</th>
            <th>Actions</th>
          </thead>
          <tbody>
            {% for tour in tours %}
              <tr>
                <td> <img src="{{tour.image.url}}" height="100"> </td>
                <td> {{ tour.title }} </td>
                <td> {{ tour.category }} </td>
                <td>

                  <div class="form-group">
                    <a href="{% url 'myadmin:myadmin-update-tour' tour.id %}" class="btn btn-info btn-sm btn-block">Update Tour</a>
                  </div>

                  <form action="{% url 'myadmin:myadmin-detail-form' tour.id %}" method="post"> {% csrf_token %}
                    <div class="form-group">
                      <input type="hidden" name="tour" value="{{ tour.id }}">
                      <button type="submit" class="btn btn-primary btn-sm btn-block">Add Detail</button>
                    </div>
                  </form>

                  <div class="form-group">
                    <a href="{% url 'myadmin:myadmin-delete-tour' tour.id %}" class="btn btn-danger btn-sm btn-block">Delete Tour</a>
                  </div>

                  <div class="form-group">
                    <a href="{% url 'myadmin:myadmin-tour-details' tour.id %}" class="btn btn-secondary btn-sm btn-block">View Details</a>
                  </div>

                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

myadmin/templates/myadmin/tours/delete_tour.html
{% extends "myadmin/base.html" %}

{% block content %}

<div class="row" id="app">
  <div class="col-md-6 offset-md-3">
    <div class="card m-b-30">
      <div class="card-body">
        <div class="form-group">
          <h4 class="text-info">Are you sure you want to delete this tour? you can make it unactive.</h4>
          <p class="text-muted">You can't undo this action.</p>
        </div>
        <form method="post"> {% csrf_token %}
            <div class="form-group">
              <button type="submit" class="btn btn-danger btn-block">Yes</button>
            </div>
        </form>
        <div class="form-group">
          <a href="{% url 'myadmin:myadmin-tours-list' %}" class="btn btn-info btn-block">No</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}