site_info/urls.py
from django.urls import path, include
from .views import about, contact, NewsLetterViewSet
from rest_framework import routers
from django.contrib.auth.decorators import login_required

router = routers.DefaultRouter()
router.register('site_info', NewsLetterViewSet)

app_name = 'site_info'

urlpatterns = [
    path('about', about, name='about-page'),
    path('contact', contact, name='contact-page'),
    path('api/newsletter/', include(router.urls))
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmintours/', include('myadmin.urls', namespace='myadmin')),
    path('summernote/', include('django_summernote.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('tours.urls', namespace='tours')),
    path('inf/', include('site_info.urls', namespace='site_info')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
from django.urls import path, include
from .views import home_page, single_tour, tours_list

app_name = 'tours'

urlpatterns = [
    path('', home_page, name='home-page'),
    path('tours/<str:tour_slug>', single_tour , name='single_tour'),
    path('all_tours_experiences/', tours_list , name='tours_list'),
]

templates/base.html
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="My city tour, where you can find amazing tours and experiences in marrakech, morocco">
  <title>{% block title %}MCT{% endblock title %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
</head>
<link rel="stylesheet" href="{% static 'site/css/main.css' %}">
<link rel="stylesheet" href="{% static 'site/css/icons.css' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'site/images/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'site/images/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'site/images/favicon-16x16.png' %}">
<link rel="manifest" href="/manifest.json">
{% block styles %}

{% endblock styles %}

<!-- Start of Async Drift Code -->
<script>
  "use strict";
  
  !function() {
    var t = window.driftt = window.drift = window.driftt || [];
    if (!t.init) {
      if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
      t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
      t.factory = function(e) {
        return function() {
          var n = Array.prototype.slice.call(arguments);
          return n.unshift(e), t.push(n), t;
        };
      }, t.methods.forEach(function(e) {
        t[e] = t.factory(e);
      }), t.load = function(t) {
        var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
        o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
        var i = document.getElementsByTagName("script")[0];
        i.parentNode.insertBefore(o, i);
      };
    }
  }();
  drift.SNIPPET_VERSION = '0.3.1';
  drift.load('z7zbhb39ccvx');
  </script>
<!-- End of Async Drift Code -->


<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand text-white" href="#">MCT</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/{{ LANGUAGE_CODE  }}">{% trans 'Home' %} <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tours:tours_list'  %}">{% trans 'Tours' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'site_info:about-page' %}">{% trans 'About' %}</a>
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn  my-2 my-sm-0" type="submit">Search</button>
        </form>

        <ul class="navbar-nav ml-auto ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle " href="/" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {% trans 'Language' %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="/fr/">Francais</a>
              <a class="dropdown-item" href="/es/">Español</a>
              <a class="dropdown-item" href="/en/">English</a>
              <a class="dropdown-item" href="/ar/">العربية</a>
            </div>
          </li>
        </ul>

        <!-- <form method="POST" class="navbar-nav"> {% csrf_token %}
        <select class="nav-item dropdown text-white" name="currency" id="currency" onchange='this.form.submit()' style="font-weight: bold !important">
          <option class="dropdown-item text-dark" value="0" >Currency</option>
          <option value="USD" class="text-dark">USD</option>
          <option value="EUR" class="text-dark">EUR</option>
          <option value="MAD" class="text-dark">MA MAD</option>
        </select>
      </form> -->

      </div>
    </div>
  </nav>
  <!-- end nav -->

  {% block content %}

  {% endblock content %}

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>
  {% block scripts %}

  {% endblock scripts %}
  <footer class="p-3 m-3">
    <div class="row">
      <div class="col-md-4 col-xs-12 text-center">
        <h3><a class="navbar-brand text-main" href="#">MCT</a></h3>
        <p class="text-muted">© 2018 MCT</p>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
      </div>
      <div class="col-md-3 col-xs-12 m-3">
        <p>Need help? <span class="text-muted">+212 6 99 99 99 99</span></p>
        <p><a href="{% url 'site_info:contact-page' %}">{% trans 'Contact' %}</a></p>
        <p><a href="#">Privacy and policy</a></p>
      </div>

      <div class="col-md-2 col-xs-12 m-3">
        <div class="styled-select">
          <b class="text-muted">{% trans "currency" %}</b>
          <form method="POST"> {% csrf_token %}
            <select class="form-control" name="currency" id="currency" onchange='this.form.submit()'>
              <option value="0" selected>--currency--</option>
              <option value="USD">USD</option>
              <option value="EUR">EUR</option>
              <option value="MAD">MA MAD</option>
            </select>
          </form>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>