myadmin/urls.py
from django.urls import  path
from django.contrib.auth.decorators import login_required
from .views import (home, add_tour,
                    add_detail, tours_list, show_detail_page,
                    update_tour, delete_tour, tour_details, tour_detail_delete,
                    tour_detail_update, check_voucher, all_orders,languages_view,
                    add_language, delete_language)


app_name = 'myadmin'

urlpatterns = [
    path('', login_required(home) , name='myadmin-home'),
    path('add-tour', login_required(add_tour) , name='myadmin-add-tour'),
    path('update-tour/<int:id>', login_required(update_tour) , name='myadmin-update-tour'),
    path('delete-tour/<int:id>', login_required(delete_tour) , name='myadmin-delete-tour'),
    path('add-detail', login_required(add_detail) , name='myadmin-add-detail'),
    path('tours-list', login_required(tours_list) , name='myadmin-tours-list'),
    path('detail-form/<int:tour>', login_required(show_detail_page) , name='myadmin-detail-form'), # made this only to send tour from tours list
    path('tour-details/<int:tour>', login_required(tour_details) , name='myadmin-tour-details'),
    path('tour-details/delete/<int:detail>', login_required(tour_detail_delete) , name='myadmin-detail-delete'),
    path('tour-details/update/<int:detail>', login_required(tour_detail_update) , name='myadmin-detail-update'),
    path('check-voucher', login_required(check_voucher), name='check-voucher'),
    path('all-orders', login_required(all_orders), name='all-orders'),
    path('languages', login_required(languages_view), name='languages'),
    path('languages/add', login_required(add_language), name='add-language'),
    path('languages/update/<int:id>', login_required(add_language), name='update-language'),
    path('languages/delete/<int:id>', login_required(delete_language), name='delete-language'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmintours/', include('myadmin.urls', namespace='myadmin')),
    path('summernote/', include('django_summernote.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('tours.urls', namespace='tours')),
    path('inf/', include('site_info.urls', namespace='site_info')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/models.py
from django.db import models

# Create your models here.

myadmin/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from tours.models import Tour, TourDetail, Language

class TourForm(forms.ModelForm):
    class Meta:
        model   = Tour
        fields  = ('title', 'from_time', 'to_time', 'availability', 'allowed_ages', 'age_senior', 'price_senior', 'age_adult', 'price_adult',
                    'age_children', 'price_children', 'age_infant', 'price_infant', 'hours', 'minutes', 'days', 'days_in_advance', 'languages', 'category',
                    'tag', 'image', 'image1', 'image2', 'image3', 'wallpaper', 'active', 'feautured')
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'id': 'title'
        }
    ))
    # from_date = forms.DateField(widget=forms.DateInput(
    #     attrs = {
    #         'class': 'form-control',
    #         'id': 'from_date',
    #         'type': 'date',
    #     }
    # ))
    # to_date = forms.DateField(widget=forms.DateInput(
    #     attrs = {
    #         'class': 'form-control',
    #         'id': 'from_date',
    #         'type': 'date'
    #     }
    # ))
    from_time = forms.TimeField(widget=forms.TimeInput(
        attrs = {
            'class': 'form-control',
            'id': 'from_time',
            'type': 'time'
        }
    ))
    to_time = forms.TimeField(widget=forms.TimeInput(
        attrs = {
            'class': 'form-control',
            'id': 'from_time',
            'type': 'time'
        }
    ))
    hours = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    minutes = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    days = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    DAYS_IN_ADVANCED = (
        ('0','NONE'),
    )
    for i in range (1,31):
        DAYS_IN_ADVANCED+= (("{}".format(i),"{}".format(i)),)
    days_in_advance = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
    choices=(DAYS_IN_ADVANCED))


class DetailsForm(forms.ModelForm):
    class Meta:
        model  = TourDetail
        fields = ['Language', 'title', 'city', 'description', 'summary', 'included', 'excluded']
        widgets = {
            'description':  SummernoteWidget(),
            'included':     SummernoteWidget(),
            'excluded':     SummernoteWidget(),
        }


class CheckVoucherForm(forms.Form):
    voucher_no = forms.CharField(max_length=100, widget=forms.TextInput(
    attrs={
        'class': 'form-control'
    }
    ))

    def clean_voucher_no(self):
        no = self.cleaned_data['voucher_no']
        if "'" in no or "(" in no or ")" in no or '"' in no:
            raise ValidationError("Use only letters and numbers.")
        else:
            return no


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ['title', 'image']
        

myadmin/views.py
from django.shortcuts import render, redirect
from checkout.models import Billing
import datetime
from django.db.models import Sum
from .forms import TourForm, DetailsForm, CheckVoucherForm, LanguageForm
from tours.models import Tour, TourDetail, Language
from checkout.models import Billing
from checkout.models import Voucher
from django.shortcuts import  get_object_or_404
import datetime


def home(request):
    orders = Billing.objects.order_by('-id')[:30]
    orders_today = Billing.objects.filter(date_order=datetime.datetime.now().date())
    today_income = orders_today.aggregate(Sum('amount'))
    total_orders = Billing.objects.all()
    total_income = total_orders.aggregate(Sum('amount'))
    context = {
        'orders': orders,
        'orders_today': orders_today,
        'today_income': today_income,
        'total_orders': total_orders,
        'total_income': total_income
    }
    return render(request, 'myadmin/home.html', context)


def add_tour(request, *args, **kwargs):
    form = TourForm()
    if request.method == 'POST':
        form = TourForm(request.POST, request.FILES)
        if form.is_valid():
            tour = form.save()
            if request.POST['action'] == 'next':
                tour = get_object_or_404(Tour, id=tour.id)
                form_detail = DetailsForm()
                return render(request, 'myadmin/tours/adddetails.html', {'tour': tour, 'form': form_detail})
            else:
                tours = Tour.objects.order_by('-id')
                return render(request, 'myadmin/tours/all-tours.html', {'added': True, "tours": tours})
    context = {
        'form': form
    }
    return render(request, 'myadmin/tours/add.html', context)


def update_tour(request, id):
    tour = get_object_or_404(Tour, id=id)
    if request.method == 'POST':
        form = TourForm(request.POST or None, request.FILES, instance=tour)
    else:
        form = TourForm(request.POST or None, instance=tour)
    if form.is_valid():
        form.save()
    return render(request, 'myadmin/tours/add.html', {"form": form, "update": True, "tour": tour})


def delete_tour(request, id):
    if request.method == 'POST':
        tour = get_object_or_404(Tour, id=id)
        tour.delete()
        tours = Tour.objects.order_by('-id')
        return render(request, 'myadmin/tours/all-tours.html', {'deleted': True, "tours": tours})
    return render(request, 'myadmin/tours/delete_tour.html')


def show_detail_page(request, tour):
    tour = get_object_or_404(Tour, id=tour)
    form_detail = DetailsForm()
    return render(request, 'myadmin/tours/adddetails.html', {'tour': tour, 'form': form_detail})


def add_detail(request):
    if request.method == 'POST':
        form = DetailsForm(request.POST)
        tour = get_object_or_404(Tour, id=request.POST['tour'])
        if form.is_valid():
            detail = form.save()
            detail.tour = tour
            detail.save()
            form = DetailsForm()
            return render(request, 'myadmin/tours/adddetails.html', {'form': form, 'success': True})
    else:
        return redirect("myadmin:myadmin-home")


def tours_list(request):
    tours = Tour.objects.order_by('-id')
    return render(request, 'myadmin/tours/all-tours.html', {'tours': tours})


def tour_details(request, tour):
    tour = Tour.objects.get(id=tour)
    details = TourDetail.objects.filter(tour=tour)
    context = {
        'tour' : tour,
        'details': details
    }
    return render(request, 'myadmin/details/tour-details.html', context)


def tour_detail_delete(request, detail):
    if request.method == 'POST':
        tour_detail = get_object_or_404(TourDetail, id=detail)
        tour_detail.delete()
        tours = Tour.objects.order_by('-id')
        return render(request, 'myadmin/tours/all-tours.html', {'deleted': True, "tours": tours})
    return render(request, 'myadmin/tours/delete_tour.html')


def tour_detail_update(request, detail):
    updated = "0"
    detail = get_object_or_404(TourDetail, id=detail)
    form = DetailsForm(request.POST or None, instance=detail)
    if form.is_valid():
        form.save()
        updated = "1"
    return render(request, 'myadmin/tours/adddetails.html', {"form": form, "updated": updated, "detail": detail})


def check_voucher(request):
    form = CheckVoucherForm()
    if request.method == 'POST':
        form = CheckVoucherForm(request.POST)
        if form.is_valid():
            no = request.POST['voucher_no']
            exists = '-'
            voucher = None
            try:
                voucher = Voucher.objects.get(No=no)
                exists = True
            except Voucher.DoesNotExist:
                exists = False

            context = {
                'form': form,
                'exists': exists,
                'voucher': voucher
            }

            return render(request, 'myadmin/voucher/check_voucher.html', context)

    return render(request, 'myadmin/voucher/check_voucher.html', {'form': form})


def all_orders(request):
    orders = Billing.objects.order_by('-id')
    context = {
        'orders':orders
    }
    return render(request, 'myadmin/orders/all_orders.html', context)


def languages_view(request):
    languages = Language.objects.all()
    context = {
        'languages': languages
    }
    return render(request, 'myadmin/language/home.html', context)

def add_language(request, *args, **kwargs):
    form = LanguageForm()
    if 'id' in kwargs:
        language = get_object_or_404(Language, id=kwargs['id'])
        form = LanguageForm(request.POST or None, instance=language)
        if request.method == 'POST':
            form = LanguageForm(request.POST, request.FILES, instance=language)
            if form.is_valid():
                form.save()
                return render(request, 'myadmin/language/home.html', {'languages': Language.objects.all()})
    if request.method == 'POST':
        form = LanguageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/myadmintours/languages')
    context = {
        'form': form
    }
    return render(request, 'myadmin/language/add.html', context)

def delete_language(request, id):
    language = get_object_or_404(Language, id=id)
    language.delete()
    return redirect('/myadmintours/languages')

templates/myadmin/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>{% block title %}{% endblock %}</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesdesign" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App Icons -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{% static 'assets/plugins/morris/morris.css' %}">

    <!-- App css -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
</head>
<body>
    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <!-- Navigation Bar-->
    <header id="topnav">
        <!-- MENU Start -->
        <div class="navbar-custom">
            <div class="container-fluid">
                <div id="navigation">
                    <!-- Navigation Menu-->
                    <ul class="navigation-menu">

                        <li class="has-submenu">
                            <a href="{% url 'myadmin:myadmin-home' %}"><i class="ti-home"></i>Home</a>
                        </li>

                        <li class="has-submenu">
                            <a href="#"><i class="ti-crown"></i>Tours</a>
                            <ul class="submenu">
                                <li><a href="{% url 'myadmin:myadmin-add-tour' %}">Add tour</a></li>
                                <li><a href="{% url 'myadmin:myadmin-tours-list' %}">All tours</a></li>
                            </ul>
                            <li><a href="{% url 'myadmin:all-orders' %}">All orders</a></li>
                            <li><a href="{% url 'myadmin:languages' %}">Languages</a></li>
                        </li>

                    </ul>
                    <!-- End navigation menu -->
                </div> <!-- end #navigation -->
            </div> <!-- end container -->
        </div> <!-- end navbar-custom -->
    </header>
    <!-- End Navigation Bar-->

    <div class="wrapper">
        <div class="container-fluid">
            {% block content %} {% endblock %}
        </div>
    </div>
    <!-- end wrapper -->


    <!-- Footer -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    © 2018 MCT - Crafted with <i class="mdi mdi-heart text-danger"></i> by I.A.
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->


    {% include 'myadmin/snippets/scripts.html' %}
    {% block script %} {% endblock %}
</body>

</html>